<!--pandoc
t: html
default-image-extension: png
template: templates/html.template
toc-depth: 4
toc:

t: latex
s:
S:
latex-engine: xelatex
template: templates/latex.template
default-image-extension: pdf
toc-depth: 4
toc:
-->

```{r echo=FALSE, cache=FALSE, results="hide"}
opts_chunk$set(echo = FALSE, fig.cap='', dev=c('png', 'pdf'), fig.width=6,
  fig.height=4)
opts_knit$set('upload.fun' = function(x) sub("\\.[[:alnum:]]*$", "", x) )
opts_chunk$set(cache.path="cache/05/")
```

# Supplementary Material
Supplementary material for:
R. W. Taylor, M. M. Humphries, S. Boutin, J. C. Gorrell, D. W. Coltman, and A. G. McAdam. Selection on female behaviour fluctuates with offspring environment. Journal of Evolutionary Biology, 2014.

Data and code used in the analyses are available on github (https://github.com/rwtaylor/2014-female-selection) and archived on Zenodo (http://dx.doi.org/10.5281/zenodo.10908)


```{r load_packages, cache=FALSE}
library(MASS) # MASS clashes with dplyr... so always load first
library(pander) # pander clashes with dplyr... so always load first
set.alignment('right', row.names = 'left')
library(dplyr)
library(MCMCglmm)
```

```{r s1}
load("mcmc_repeatability_summary.RData")
table_summary <- as.matrix(table_summary)
dimnames(table_summary)[[2]] <- c("Behavior", "Overall Repeatability", "Repeatability Within Years", "Repeatability Across Years")
pandoc.table(table_summary, caption = "Repeatability within and across years. Repeatabilities were estimated using linear mixed effects models with individual as a random effect. Repeatability across years was estimated after randomly sampling, for each individual, only one behavioural measure per year.")
```

```{r s2}
load("data/analyses_data/fit_raneff_data.RData")
fit_data <- fit_raneff_data %>% filter(type == "blup") %>% filter(!is.na(aggression) & !is.na(activity) & !is.na(docility))
```

